# Generated by Django 5.1.4 on 2025-01-10 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vedaapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseMaster',
            fields=[
                ('purchaseID', models.AutoField(primary_key=True, serialize=False)),
                ('quantityPurchased', models.IntegerField()),
                ('purchasePrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchaseDate', models.DateTimeField(auto_now_add=True)),
                ('purchasedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockMaster',
            fields=[
                ('stockID', models.AutoField(primary_key=True, serialize=False)),
                ('itemName', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('supplierName', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='ProductGallery',
            new_name='PlantGallery',
        ),
        migrations.RenameModel(
            old_name='ProductMaster',
            new_name='PlantMaster',
        ),
        migrations.DeleteModel(
            name='ServiceMaster',
        ),
        migrations.DeleteModel(
            name='TeamMember',
        ),
        migrations.AddField(
            model_name='purchasemaster',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vedaapp.stockmaster'),
        ),
    ]
