# Generated by Django 5.1.4 on 2025-01-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vedaapp', '0003_alter_purchasemaster_purchasedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmaster',
            name='supplierName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
