# Generated by Django 5.1.4 on 2025-01-12 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vedaapp', '0004_alter_stockmaster_suppliername'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchasemaster',
            options={'ordering': ['-purchaseDate'], 'verbose_name': 'Purchase Record', 'verbose_name_plural': 'Purchase Records'},
        ),
        migrations.AlterField(
            model_name='purchasemaster',
            name='purchasedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchasemaster',
            name='quantityPurchased',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='purchasemaster',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='vedaapp.stockmaster'),
        ),
    ]
