# Generated by Django 5.1.4 on 2025-02-07 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vedaapp', '0006_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymaster',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='vedaapp.categorymaster'),
        ),
        migrations.AlterField(
            model_name='categorymaster',
            name='catName',
            field=models.CharField(max_length=18, unique=True),
        ),
    ]
