# Generated by Django 5.1.5 on 2025-02-08 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vedaapp', '0007_categorymaster_parent_alter_categorymaster_catname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorymaster',
            options={'ordering': ['catName'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='categorymaster',
            name='catName',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='categorymaster',
            name='image',
            field=models.ImageField(blank=True, default='category_images/default.jpg', null=True, upload_to='category_images/'),
        ),
        migrations.AlterField(
            model_name='categorymaster',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='vedaapp.categorymaster'),
        ),
    ]
