# Generated by Django 5.1.1 on 2025-03-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vedaapp', '0013_orderstatuslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('packaged', 'Packaged'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
